### ISSUE TITLE
Non-Default Gripper Angles

### ISSUE THREAD

**Issue by TomShkurti** [cwru-robotics/cwru_davinci_kinematics#11]
When inverse kinematics is given a position with a non-default (i.e. not straight down) gripper angle, it will produce a joint vector that does not exactly correspond thereto. Specifically, the X and Y components of the location will be offset by the length of the gripper (i.e. ~2cm), as though the position is being measured from the origin of the wrist and not the gripper tip. The Z component will not be affected and will be reached properly.

For instance, giving IK the position 0.0, 0.0, -0.10,   0.0, 0.0, 1.0,    1.0, 0.0, 0.0 (down 10cm, gripper pointing to the left) will result in the tip moving to the point **-0.02**, 0.0, -0.1.

If given such a joint state FK will then accurately report the real position as opposed to the desired.

**Comment by biocubed** [comment]
@TomShkurti I am confused by your example position : 0.0, 0.0, -0.10, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0  there are 9 numbers. There should only be 7 correct?

**Comment by TomShkurti** [comment]
Determined that the error only becomes significant when very close to the 90-degree-gripper-angle edge case. Closing.
